In [5]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline

data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name="Target")

X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

In [7]:
X[:5]

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
#Train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy:", acc)

Test Accuracy: 0.956140350877193

In [10]:
#pipline
pipepline=Pipeline([('scaler',StandardScaler()),('svm',SVC())])

param_grid_linear = {
    'svm__kernel': ['linear'],
    'svm__C': [0.1, 1, 10]
}

grid_linear = GridSearchCV(
    pipepline,
    param_grid_linear,
    cv=5,
    scoring='accuracy'
)

grid_linear.fit(X_train, y_train)

print("LINEAR Kernel Best Params:", grid_linear.best_params_)
print("LINEAR Kernel Accuracy:", grid_linear.best_score_)

LINEAR Kernel Best Params: {'svm__C': 0.1, 'svm__kernel': 'linear'}
LINEAR Kernel Accuracy: 0.9736263736263737

In [11]:
param_grid_poly = {
    'svm__kernel': ['poly'],
    'svm__C': [0.1, 1, 10],
    'svm__degree': [2, 3]
}

grid_poly = GridSearchCV(
    pipepline,
    param_grid_poly,
    cv=5,
    scoring='accuracy'
)

grid_poly.fit(X_train, y_train)

print("POLY Kernel Best Params:", grid_poly.best_params_)
print("POLY Kernel Accuracy:", grid_poly.best_score_)

POLY Kernel Best Params: {'svm__C': 10, 'svm__degree': 3, 'svm__kernel': 'poly'}
POLY Kernel Accuracy: 0.9538461538461538

In [12]:
param_grid_rbf = {
    'svm__kernel': ['rbf'],
    'svm__C': [0.1,1,10],
    'svm__gamma':[0.1,1,10]
}

grid_rbf = GridSearchCV(
    pipepline,
    param_grid_rbf,
    cv=5,
    scoring='accuracy'
)
grid_rbf.fit(X_train, y_train)

print('RBF Kernel BEst Params:',grid_rbf.best_params_)
print('RBF Kernel Accuracy:',grid_rbf.best_score_)

RBF Kernel BEst Params: {'svm__C': 1, 'svm__gamma': 0.1, 'svm__kernel': 'rbf'}
RBF Kernel Accuracy: 0.9604395604395604

In [13]:
param_grid_sigmoid = {
    'svm__kernel': ['sigmoid'],
    'svm__C': [0.1,1,10],
    'svm__gamma':[0.1,1,10]
}

grid_sigmoid = GridSearchCV(
    pipepline,
    param_grid_sigmoid,
    cv=5,
    scoring='accuracy'
)
grid_sigmoid.fit(X_train, y_train)


print('SIGMOID Kernel BEst Params:',grid_sigmoid.best_params_)
print('SIGMOID Kernel Accuracy:',grid_sigmoid.best_score_)

SIGMOID Kernel BEst Params: {'svm__C': 0.1, 'svm__gamma': 0.1, 'svm__kernel': 'sigmoid'}
SIGMOID Kernel Accuracy: 0.9626373626373625

In [14]:

param_grid_linear = {
    'svm__kernel': ['linear'],
    'svm__C': [0.1, 1, 10]
}

grid_linear = GridSearchCV(
    pipepline,
    param_grid_linear,
    cv=10,
    scoring='accuracy'
)

grid_linear.fit(X_train, y_train)

print("LINEAR Kernel Best Params:", grid_linear.best_params_)
print("LINEAR Kernel Accuracy:", grid_linear.best_score_)

LINEAR Kernel Best Params: {'svm__C': 0.1, 'svm__kernel': 'linear'}
LINEAR Kernel Accuracy: 0.9780676328502415

In [15]:
param_grid_poly = {
    'svm__kernel': ['poly'],
    'svm__C': [0.1, 1, 10],
    'svm__degree': [2, 3]
}

grid_poly = GridSearchCV(
    pipepline,
    param_grid_poly,
    cv=10,
    scoring='accuracy'
)

grid_poly.fit(X_train, y_train)

print("POLY Kernel Best Params:", grid_poly.best_params_)
print("POLY Kernel Accuracy:", grid_poly.best_score_)

POLY Kernel Best Params: {'svm__C': 10, 'svm__degree': 3, 'svm__kernel': 'poly'}
POLY Kernel Accuracy: 0.953719806763285

In [16]:
param_grid_rbf = {
    'svm__kernel': ['rbf'],
    'svm__C': [0.1,1,10],
    'svm__gamma':[0.1,1,10]
}

grid_rbf = GridSearchCV(
    pipepline,
    param_grid_rbf,
    cv=10,
    scoring='accuracy'
)
grid_rbf.fit(X_train, y_train)

print('RBF Ki BEst Params:',grid_rbf.best_params_)
print('RBF Kernel Accuracy:',grid_rbf.best_score_)

RBF Ki BEst Params: {'svm__C': 1, 'svm__gamma': 0.1, 'svm__kernel': 'rbf'}
RBF Kernel Accuracy: 0.9581642512077295

In [17]:
param_grid_sigmoid = {
    'svm__kernel': ['sigmoid'],
    'svm__C': [0.1,1,10],
    'svm__gamma':[0.1,1,10]
}

grid_sigmoid = GridSearchCV(
    pipepline,
    param_grid_sigmoid,
    cv=10,
    scoring='accuracy'
)
grid_sigmoid.fit(X_train, y_train)


print('SIGMOID Kernel BEst Params:',grid_sigmoid.best_params_)
print('SIGMOID Kernel Accuracy:',grid_sigmoid.best_score_)

SIGMOID Kernel BEst Params: {'svm__C': 0.1, 'svm__gamma': 0.1, 'svm__kernel': 'sigmoid'}
SIGMOID Kernel Accuracy: 0.9516425120772947

In [18]:
param_grid_sigmoid = {
    'svm__kernel': ['sigmoid'],
    'svm__C': [0.1,1,10],
    'svm__gamma':[0.1,1,10]
}

grid_sigmoid = GridSearchCV(
    pipepline,
    param_grid_sigmoid,
    cv=10,
    scoring='accuracy'
)
grid_sigmoid.fit(X_train, y_train)


print('SIGMOID Kernel BEst Params:',grid_sigmoid.best_params_)
print('SIGMOID Kernel Accuracy:',grid_sigmoid.best_score_)

SIGMOID Kernel BEst Params: {'svm__C': 0.1, 'svm__gamma': 0.1, 'svm__kernel': 'sigmoid'}
SIGMOID Kernel Accuracy: 0.9516425120772947